1)
Answer: DE
Section: All

Explanation/Reference:
End of method.
run.
Exception in thread "Thread-0" java.lang.RuntimeException: Problem
at Threads2.run(Threads2.java:5)
at java.lang.Thread.run(Unknown Source)

2)
Answer: AF Section: All

3)

Answer: B Section: All

Explanation/Reference: Threads2.java:15: unreported exception java.lang.InterruptedException; must be caught or declared to be thrown. obj.wait(); ^ 1 error

The answer appears before the correction was "This code can throw an IllegalMonitorStateException. "But exceptions are used IllegalMonitorStateException

4)
Answer: D Section: All

Explanation/Reference:

5)
Answer: B Section: All

Explanation/Reference: The answer you get is second sequence number n-1 n-2 n-1 n-2

6)
Answer: B Section: All

Explanation/Reference:

fooException in thread "main" java.lang.IllegalThreadStateException at java.lang.Thread.start(Unknown Source) at p6.Threads4.go(Threads4.java:15) at p6.Threads4.main(Threads4.java:5)

7)Answer: BE Section: All

8)
Answer: D Section: All

Explanation/Reference: The method go(String[], int) in the type Barn is not applicable for the arguments (String, int) The variable argument type String of the method go must be the last parameter

9)
Answer: D Section: All

Explanation/Reference:

10)
Answer: C Section: All

Explanation/Reference: The return type is incompatible with B.execute()


